### ISSUE TITLE
Correggere visualizzazione clessidra

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#104]
L'immagine placeholder della clessidra nella `UserProfileActivity` non viene visualizzata; controllare se funziona lo scale drawable altrimenti sostituirlo

**Comment by marcocadei** [comment]
Vedere se si può mettere lo stesso placeholder anche nella bacheca nel caricamento delle immagini

**Comment by marcocadei** [comment]
Vedere se si può mettere l'animazione alla clessidra (**ULTRA MINOR**)

**Comment by AndreaPitossi** [comment]
Solo cambiarle colore: primary dark
