### ISSUE TITLE
Completamento sezione rewards

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#111]
Alcuni dettagli ancora da sistemare:
- sistemare aggiornamento di userhome (scalare punti, aggiornare statistiche) una volta che lo stato aggiornato in real-time è disponibile
- aggiungere empty list message (da adattare al caso particolare dei premi, perchè in realtà il premio in denaro è sempre visualizzato)
- rendere facoltativa descrizione

**Comment by marcocadei** [comment]
Lo stato aggiornato in real-time è adesso disponibile

**Comment by gianluca150** [comment]
Tutto realizzato (la descrizione non è più facoltativa ma obbligatoria come stabilito)
