### ISSUE TITLE
Gestione permessi bacheca

### ISSUE THREAD

**Issue by marcocadei** [MarcoCadei/APPartment#115]
Definire permessi per **chi** può eliminare **quali** post in bacheca.
Una volta stabilito implementare di conseguenza (è solamente questione di non mostrare l'immagine che consente di aprire il popup menù)

**Comment by AndreaPitossi** [comment]
Io personalmente direi che ognuno può cancellare i propri ovviamente e che master e proprietario possono cancellare anche quelli degli altri (penso ad esempio al caso dei genitori che devono cancellare messaggi stupidi dei bambini)

**Comment by gianluca150** [comment]
Implementato così come indicato da @AndreaPitossi nell'ultimo commento
