### ISSUE TITLE
Gestione errori sezione rewards

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#116]
Copia del messaggio di slack:
>il problema è sempre che dalla RewardDetailActivity in avanti (perché a questo punto anche nell'activity di modifica visto come l'abbiamo implementata ieri) non abbiamo più i dati "sincronizzati in real-time", quindi ok la modifica abbiamo deciso che ce ne sbattiamo, ma nel caso in cui io sto visualizzando un dettaglio di un premio che nel frattempo viene eliminato da un master dopo quando schiaccio i bottoni avviene una scrittura che [nel momento in cui avremo impostato delle regole di sicurezza "serie" per firebase] viene rimbalzata, e quindi ce ne dobbiamo accorgere per mostrare almeno una snackbar o che ne so

**Comment by marcocadei** [comment]
Questo problema si può verificare solamente per i `Reward` e i `Todo`, corretto @gianluca150 ?
