### ISSUE TITLE
Apertura immagine di profilo in UserProfileActivity

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#122]
L'apertura dell'immagine di profilo taglia un po' l'immagine

**Comment by marcocadei** [comment]
Purtroppo per come stanno le cose non si può fare.
Sono riuscito a risolvere il glitch che si aveva quando si passava da immagine quadrata a tonda, ma il fatto che venga un po' tagliata non si può evitare. Questo è dovuto al fatto che lo scale type è `cropCenter` mentre a noi servirebbe `fitCenter` che purtroppo però non si può usare. Sulla repo della libreria stessa c'è la issue con il problema, ma non la caga nessuno (https://github.com/vikramkakkar/ImageTransition/issues/2). 
Questo è il problema di usare le librerie marce, però era anche l'unica che faceva sta cosa.

**Comment by marcocadei** [comment]
L'**unica** possibile soluzione è agire a monte: vedere se esiste una libreria che (stile WhatsApp) consente di tagliare l'immagine in fase di upload. Facendo così si risolve il problema in quanto anche ora se si carica l'immagine tonda in una quadrata 200dpx200dp allora non c'è più alcun taglio.

**Comment by marcocadei** [comment]
Libreria che potrebbe fare ciò che ci serve
https://github.com/ArthurHub/Android-Image-Cropper
