### ISSUE TITLE
Aggiungere il LiveData loading in tutti i fragment

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#126]
Per tutte le operazioni (modifica, prenotazione, ...) che richiedono di uscire dalla lista e rientrare con un aggiornamento
Prendere ispirazione dalla bacheca (MessagesFragment)

**Comment by marcocadei** [comment]
È davvero necessario? Nella bacheca serviva perché si caricano dei media e il tempo di attesa è sempre ben visibile, ma negli altri casi (modifica di un membro della casa, modifica delle cose da fare, modifica dei premi) il 99% delle volte (quando internet va bene) vedi un flash arancione per una frazione di secondo e non è tanto bello.

**Comment by gianluca150** [comment]
bro make up your mind. questa issue l'abbiamo messa perché sei stato tu a dire che andava fatta la cosa
però mi ricordo che avevi dato una motivazione sensata, ora non mi ricordo però c'era un motivo che c'aveva portato a decidere di farlo

**Comment by gianluca150** [comment]
ah sì, forse era legato alla gestione degli errori? che è comunque una parte che non abbiamo ancora fatto quindi non saprei dirti i dettagli

**Comment by marcocadei** [comment]
Eh boh son, adesso la gestione degli errori e della presenza della rete c'è e non vedo necessità di inserirlo. Tuttavia, se mi trovi una motivazione sensata ce lo piazzo senza problemi

**Comment by gianluca150** [comment]
Bella domanda, io direi lasciamola aperta just in case e poi alla fine se non c'è ancora venuto in mente nulla chiudiamo
