### ISSUE TITLE
Controlli form

### ISSUE THREAD

**Issue by marcocadei** [MarcoCadei/APPartment#128]
Verificare in tutte le form che ci siano i controlli necessari

**Comment by gianluca150** [comment]
Per ora tutte le 6 activity che contengono una form (CreateHome, CreateReward, CreateTask, JoinHome, SignIn, SignUp) estendono `FormActivity` e definiscono un override di `checkInput`.
Chiudo questa issue, per altri problemi specifici relativi a controlli particolari di una delle form aprire una issue specifica
