### ISSUE TITLE
Problema animazione da/verso DoneFragment

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#135]
~~In questo passaggio l'animazione di scorrimento si ha solo per l'intestazione e non per il corpo del fragment~~

**Comment by gianluca150** [comment]
[premesso che è tutto da valutare dopo #143 (presenza o meno dell'ordinamento nell app)]

potrebbe essere che siccome ci sono due animazioni innestate (fragment nella MainActivity e fragment quello del tab) si "sovrappongono" e viene fuori l'effetto che vediamo. vedere se cambia qualcosa dopo aver risolto #119, nel caso provare anche qui a togliere la "prima" animazione e vedere se si risolve il problema

**Comment by gianluca150** [comment]
Nel DoneFragment ci sono ancora le animazioni manuali (non ViewPager, che NON va messo), ma quella iniziale va tolta per evitare un brutto effetto grafico quando si entra nel DoneFragment
