### ISSUE TITLE
Fornire possibilità di eliminare task completato e cronologia di un task completato

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#142]

**Comment by marcocadei** [comment]
Se mettiamo la possibilità di eliminare la cronologia di un task completato, è possibile ritrovarsi nella paradossale situazione di un task che è nella sezione completati, ma senza alcun record per la cronologia

**Comment by gianluca150** [comment]
È paradossale solo per te, è ovvio anche per mia nonna che se è lì senza cronologia significa che _hai per l'appunto cancellato la cronologia_ :>

**Comment by AndreaPitossi** [comment]
Volete aggiungere un messaggio del tipo "La cronologia è stata cancellata" just to be safe?

**Comment by gianluca150** [comment]
Andata, direi che mettere un messaggio ci sta
