### ISSUE TITLE
Realizzare sezione premio in denaro

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#153]
(da definire cos'è che ci va dentro)

**Comment by AndreaPitossi** [comment]
Siamo ancora dell'idea di fornire la possibilità di pagare via PayPal?

**Comment by marcocadei** [comment]
> Siamo ancora dell'idea di fornire la possibilità di pagare via PayPal?

Assolutamente no. Lasciamo quell'opzione e ipotizziamo che il pagamento avvenga di persona. Altrimenti se non convince possiamo proprio piallare

**Comment by AndreaPitossi** [comment]
Perfetto così allora... per me ci sta, basta che i messaggi all'interno siano chiari
