### ISSUE TITLE
Layout fragment bacheca

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#16]
Da verificare se è possibile seguire l'idea iniziale di usare la bacheca sia per messaggi testuali sia per contenuti audio/video

DA FARE:

- per la registrazione però direi che quando si entra in modalità recording tutto il resto (testo e selezione immagine) dovrebbe essere disabilitato

- mentre una cosa che farei adesso è ingrandire un pelo i bottoni
il mio parere personale è che siano un po' piccoli, io li farei giusto un pelo più grossi (e spaziati), o al limite lascerei i simboli così come sono ora ma "cerchiati" per far uscire un pulsante tondo tipo quelli che ci sono su whatsapp e telegram per inviare il messaggio
sottinteso, si va sempre per la maggioranza, se per voi la dimensione non è un problema li lasciamo come sono ora e amen

**Comment by marcocadei** [comment]
Update: la bacheca viene usata per messaggi testuali

**Comment by marcocadei** [comment]
Update: la bacheca viene usata anche per le immagini

**Comment by marcocadei** [comment]
Update: alla bacheca è possibile aggiungere testo, immagini e audio. 
Tutti gli elementi sono contenuti in card, ciascuna delle quali ha un titolo che è il sender del messaggio.
Gli audio sono riproducibili.

DA FARE ANCORA:
Gestione dell'eliminazione dei post
Gestione degli audio tramite un player con 'seek bar' (optional, da fare se rimane tempo)

**Comment by marcocadei** [comment]
**V** Rendere grigio il bottone di invio e immagine mentre si registra un vocale (realizza utilizzando i colori che cambiano in base allo stato dell'elemento, che nel mio caso è enable = true o false)
**V** Fixare stringa riproduzione (riguarda anche le altre)
**V** Associa ai post una data e visualizzala
**V** Togli immagini da 36 e 30dp usa quelle da 24dp con l'attributo scaleType="fitCenter" e poi cambia layout_width/height
**V**  Consentire la riproduzione di un solo audio alla volta
