### ISSUE TITLE
Layout fragment to-do list

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#18]
Questa schermata contiene la lista delle attività ancora da fare

**Comment by marcocadei** [comment]
DA FARE:
- ~~Prova a fixare date picker~~
- ~~Metti selezione date con il calendario (no spinner)~~
- ~~Nella form di creazione metti prima scadenza e poi descrizione~~

**Comment by marcocadei** [comment]
Cambio compiti come accordato IRL
