### ISSUE TITLE
Eliminazione user

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#186]
Valutare se vale la pena di dare all'utente la possibilità di eliminarsi dall'app (si intende User, non HomeUser)

**Comment by marcocadei** [comment]
Io dico di no, ma vince la maggioranza.
@gianluca150 @AndreaPitossi decidete

**Comment by AndreaPitossi** [comment]
Ush... direi di no

**Comment by gianluca150** [comment]
Vabbeh, allora con due no vince la maggioranza
Tra l'altro questo implica che non possiamo mettere l'app sul play store siccome non sarebbe GDPR-compliant, quindi direi che siamo automaticamente d'accordo anche su questa questione 😘

**Comment by marcocadei** [comment]
> Tra l'altro questo implica che non possiamo mettere l'app sul play store siccome non sarebbe GDPR-compliant, quindi direi che siamo automaticamente d'accordo anche su questa questione

Ottimo, mi metto al lavoro per farlo
