### ISSUE TITLE
Layout fragment attività completate

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#19]
Questa schermata secondo il prototipo è organizzata su tre tab (tutti, frequenti, recenti) ognuno dei quali mostra una lista di attività già completate; accanto al nome di ogni attività ci sono due pulsanti, uno per accedere ai dettagli e l'altro per creare una nuova attività a partire dai dati di quella già completata

**Comment by marcocadei** [comment]
Nuova descrizione

> allora, la struttura che mi sembra avevamo pensato per i task completati "al volo" è la seguente, ma ovviamente ora che la esplicito sentiamo i vostri pareri e ci mettiamo d'accordo su quella definitiva da implementare.
il fragment di per sé contiene due tab, il primo è "tutti" e il secondo è "recenti"
ogni tab contiene una lista i cui elementi sono strutturati nello stesso modo, cambia solo l'ordinamento in cui sono visualizzati in pratica
"tutti" contiene la lista di tutti i task completati ordinati A>Z, "recenti" contiene solo gli N più recenti in base alla `lastCompletionDate`
in entrambi i casi i task sono sempre "*raggruppati per nome*"; cioè non ci sono N task "taglia il prato" ma in ogni lista compare sempre e solo *un* "taglia il prato" (questo perché avevamo deciso di implementare la "cronologia", vedi sotto; comunque questo ha più a che fare col modo in cui viene fatto il salvataggio nel db, a questo livello ci dobbiamo preoccupare solo di leggere da `/completed-tasks` assumendo che il suo contenuto sia già corretto)
sul cosa visualizzare nel singolo elemento della lista oltre al nome che sicuramente ci va lascerei decidere a voi, per me è indifferente se ultima descrizione o ultima completion date. tenete presente però che come da prototipo iniziale ogni item della lista deve avere DUE bottoni: il primo è un "aggiungi" che semplicemente apre la `CreateTaskActivity` fillandola con i dati del task che è stato selezionato, il secondo è un "dettaglio" e apre una nuova activity che appunto contiene il dettaglio del completed-task selezionato.
in quest'ultima activity di dettaglio ci sono nome punti descrizione ecc nel solito formato così come avviene già per il dettaglio degli uncompleted-tasks; la differenza è che oltre a questo sotto c'è una lista di tutti i completamenti, in pratica una sorta di "cronologia" che contiene l'elenco di tutte le volte che il task con quel nome è stato completato, in che data e da chi
per fare un esempio, quando schiacci sul dettaglio di "taglia il prato" in quell'activity vedrai nella cronologia semplicemente un elenco di chi ha completato un task con *quel nome* in passato, per esempio: "Andrea 18/04/2019; Gianluca 18/05/2019; (eccetera)". ipotizzo che questa lista non abbia lo stesso stile delle altre perché la dobbiamo mantenere molto "compatta" (la cronologia può essere anche molto lunga), per esempio farei che il singolo item è una riga di testo `textSmall` e nulla di più.
dall'activity di dettaglio del completed-task presumo che non si possa fare nulla; non ne avevamo parlato actually ma ora che m'è venuto in mente forse l'unica cosa che ha senso mettere è un bottone "cancella cronologia" che può essere usato per (you'll never guess) cancellare la cronologia
