### ISSUE TITLE
Problema con servizio Emilia Romagna

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#194]
All'apertura della pagina può capitare (mio telefono) che il numero non venga visualizzato (per via delle dimensioni dello schermo); solo che allo stato attuale non si può scrollare, perché al primo tocco la pagina si chiude

**Comment by marcocadei** [comment]
Il problema non è solo per il telefono del mastro, ma tutti i telefoni di dimensioni normali (aka, non l'elmulatore)

**Comment by gianluca150** [comment]
Risolto in #228
