### ISSUE TITLE
Uniformare le activity con bottoni in fondo a quelle che hanno una lista

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#196]
Mantenere i bottoni fissi e far scrollare solo la parte sopra

**Comment by AndreaPitossi** [comment]
CompletedTaskDetail vs RewardDetail

**Comment by marcocadei** [comment]
Qui vogliamo che i bottoni siano in basso sempre, giusto?
Vogliamo che siano in basso anche se sopra non c'è una lista, come in `RewardDetail`?
@gianluca150 @AndreaPitossi

**Comment by marcocadei** [comment]
Verificato che è impossibile ottenere il comportamento desiderato, quindi si droppa
