### ISSUE TITLE
Mettere limite massimo punti utente

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#197]

**Comment by marcocadei** [comment]
Questo perché lo vogliamo fare? (questa issue proprio non mi ricordo quando è stata aggiunta)

**Comment by AndreaPitossi** [comment]
Se non ricordo male... era per evitare l'overflow (era capitato che con tre todo con il massimo dei punti i punti dell'utente diventassero negativi)

**Comment by gianluca150** [comment]
Confermo quanto detto da @AndreaPitossi
