### ISSUE TITLE
Aggiungere funzionalità di annullamento richiesta premio a chi l'ha richiesto

### ISSUE THREAD

**Issue by AndreaPitossi** [MarcoCadei/APPartment#199]

**Comment by marcocadei** [comment]
Questo alla fine abbiamo deciso che lo facciamo?
Perché in caso allora vorrei evidenziare un'ulteriore incoerenza: se segno un'attività come completata non posso annullare quanto fatto.
Io sono dell'opinione o di non fare nessuna delle due o entrambe

**Comment by AndreaPitossi** [comment]
Sinceramente credo sia differente....se un'attività l'ho fatta allora segno la segno come completata e fine... non sussiste il concetto di cambio idea qui...
Per un premio invece posso pensare di volere un premio e poi cambiare idea per un motivo o per l'altro e prenderne un altro...
Certo entrambe hanno in comune il fatto di poter sbagliare nel farlo.... però non la prenderei proprio in considerazione come cosa
