### ISSUE TITLE
Rendere rosso il positive button nel DeleteHomeUserConfirmationDialogFragment

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#200]
Fare attenzione che lo stile del positive button è usato anche in altri dialog fragment, non va bene modificarlo a livello globale direttamente in styles

**Comment by marcocadei** [comment]
Anche il bottone di conferma di eliminazione della casa deve essere rosso?

**Comment by gianluca150** [comment]
è lo stesso bottone, `DeleteHomeUserConfirmationDialogFragment` viene riciclato per diverse situazioni cambiando solo il messaggio
