### ISSUE TITLE
Layout activity dettaglio singolo membro

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#21]
(Nel prototipo avevamo disegnato la schermata senza toolbar e bottom navigation quindi è un'activity a sè stante?)

Questa schermata contiene il dettaglio del singolo membro della famiglia.

Questioni:
- Dev'essere scrollabile tutta la schermata o solo la lista degli achievements?
- Gli achievements vengono solo visualizzati e basta o se ci si schiaccia sopra succede qualcosa / si va da qualche altra parte?

**Comment by marcocadei** [comment]
@AndreaPitossi te l'ho assegnata perché so che stai facendo tu quella della famiglia e l'unico modo per accedere a questa schermata è da quella che stai sviluppando tu, quindi direi che ha senso che faccia tu questa
