### ISSUE TITLE
Impostare regole sicurezza Firebase

### ISSUE THREAD

**Issue by marcocadei** [MarcoCadei/APPartment#43]
Impostare delle regole di sicurezza sensate per Firebase

**Comment by marcocadei** [comment]
Che regole vanno fatte ancora?
Io oggi le ho aggiornate in modo tale che vengano fuori dei `Permission Denied` se si modifica qualcosa che è stato eliminato da qualcun'altro nel frattempo.

**Comment by AndreaPitossi** [comment]
Ricontrollare tutte le 4 activity nei casi di errore (nome casa già esistente, nome utente già occupato, etc) dopo aver definito le regole di sicurezza finali che tutto vada come previsto e che la gestione degli errori è compatibile con le violazioni che si verificano
