### ISSUE TITLE
Sign-in/up

### ISSUE THREAD

**Issue by marcocadei** [MarcoCadei/APPartment#44]
Implementare funzionalità di registrazione ed accesso all'app:

DA FARE:
**V** Realizzare meccanismo registrazione
**V** Realizzare meccanismo login
- Inserire controlli form
- Impedire di poter tornare indietro una volta terminato il login o la registrazione

**Comment by gianluca150** [comment]
Ecco ma a proposito: tolto che non riusciremo a far sì che man mano che si cambia il fragment visualizzato nella main activity schiacciando il tasto indietro si ritorna al fragment visualizzato in precedenza (che sicuramente va nelle minuzie che non faremo per mancanza di tempo), quando si schiaccia la freccia indietro sul "primo" fragment visualizzato nella main activity cos'è che vogliamo che succeda? uscita? chiusura dell'app? logout?
Oppure si potrebbe semplicemente realizzare un comportamento agli effetti esterni analogo a quello che si verifica schiacciando la freccia indietro dalla enter activity: l'app in sè viene ""chiusa"", inteso che si torna al launcher del telefono, ma rimane nell'elenco di quelle aperte e se la si ""riapre"" si ritorna alla stessa schermata di prima (sicuramente questo comportamento ha un nome preciso ma io non lo conosco)

**Comment by marcocadei** [comment]
> Oppure si potrebbe semplicemente realizzare un comportamento agli effetti esterni analogo a quello che si verifica schiacciando la freccia indietro dalla enter activity: l'app in sè viene ""chiusa"", inteso che si torna al launcher del telefono, ma rimane nell'elenco di quelle aperte e se la si ""riapre"" si ritorna alla stessa schermata di prima (sicuramente questo comportamento ha un nome preciso ma io non lo conosco)

Esattamente questo, mi sembra quello che succede di norma in quasi tutte le app.
Per quanto riguarda la prima proposta: per me si può fare (i fragment possono essere aggiunti al backstack come le activity), ma non so se è quello che vorrei? Conosci qualche app che fa una cosa del genere? Perché a me forse farebbe un po' strano dato che passo da una schermata ad un'altra, ma cambia solo il contenuto e sotto posso sempre navigare. In un certo senso è come nei tab, in cui infatti il tasto indietro non mi riporta al tab in cui ero prima. 
Comunque voteremo per il comportamento che preferiamo non appena ci arriviamo.
