### ISSUE TITLE
Ristrutturazione classi del model

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#55]
Modificare le classi Task Member Home ecc. in modo che corrispondano ai dati che di questi oggetti salviamo nel database (in questo modo possiamo usare direttamente l'oggetto per l'operazione di scrittura senza dover elaborare gli attributi uno alla volta)

**Comment by marcocadei** [comment]
Fatto da @AndreaPitossi e chiuso insieme da me e @gianluca150
