### ISSUE TITLE
Gestione "corretta" del logout

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#56]
Per ora il logout semplicemente fa ripartire la EnterActivity attraverso un Intent in cui è impostato il flag `FLAG_ACTIVITY_CLEAR_TASK`, ma in teoria per gestire in modo "pulito" la cosa bisognerebbe notificare tutte le altre activity precedentemente aperte che si è verificato il logout così che queste possano terminarsi in autonomia
Source: https://stackoverflow.com/a/3008684

**Comment by gianluca150** [comment]
Update: non sono necessari i broadcasts perchè Firebase ha già le sue cose (vedere addAuthStateListener per riferimento)

**Comment by marcocadei** [comment]
Non capisco esattamente quale sia il problema.
Il tipo nella domanda di SO dice che riesce a ritornare alle activity in cui l'utente deve essere loggato e quindi questo diventa un problema, ma noi una volta che facciamo il logout dalla `UserProfileActivity` e siamo nella `EnterActivity` non abbiamo più modo di tornare alle activity che richiedono l'utente loggato.
Inoltre quando chiudiamo un activity (sia perché premiamo indietro, ma anche quando si completa qualcosa e si esce dall'activity) facciamo sempre `finish()` quindi lo stack dovrebbe essere vuoto.

**Comment by gianluca150** [comment]
No ok, nel tempo il problema originale è sicuramente mutato
Se vogliamo la massima sicurezza dovremmo comunque inserire gli `addAuthStateListener` di Firebase visto che a priori puoi essere sloggato in qualunque momento, lo scopo era quello di pararsi il sedere nei casi in cui non sei tu esplicitamente a schiacciare logout

**Comment by marcocadei** [comment]
No aspé a cosa servono gli `addAuthStateListener`? 
> a priori puoi essere sloggato in qualunque momento

Intendi sloggato dalla casa? Per quello c'è #164 
Se intendi sloggato proprio a livello di utente non capisco chi è che potrebbe sloggarti se non tu stesso?

**Comment by gianluca150** [comment]
A livello di utente tecnicamente può darsi che l'oggetto `Auth` di Firebase ti kicki fuori se succede qualche circostanza particolarissima

**Comment by marcocadei** [comment]
Ohhhhh jesus, quindi che vogliamo fare?
