### ISSUE TITLE
Refactoring activity login/registrazione

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#57]
~~Fare una classe astratta di cui tutte le activity sono sottoclassi per tagliare sul codice duplicato~~

Aggiornare la classe creata allineandola alla struttura definita per le classi che interagiscono col db

**Comment by marcocadei** [comment]
Questo non è stato fatto? @gianluca150

**Comment by gianluca150** [comment]
Adesso che abbiamo modificato la struttura delle activity di login/registrazione con lo spostamento del codice di firebase eccetera forse si può risistemare meglio anche `FormActivity`, ci guarderò appena riesco

**Comment by gianluca150** [comment]
Allora, più o meno `FormActivity` com'è va bene; volendo l'unica altra generalizzazione che si può fare sarebbe spostare gli oggetti `Auth`, `DatabaseReader` e `DatabaseWriter` direttamente nella classe astratta `FormActivity` così poi vengono ereditati da tutti. Ci sono alcune activity che tipo il writer o il reader non lo usano ma tecnicamente in quel caso va bene lo stesso (la creazione di una nuova istanza viene comunque fatta nelle sottoclassi, se un oggetto non lo si usa basta non fare l'istanziazione)
Se volete faccio anche questa modifica sennò lasciamo così com'è

**Comment by gianluca150** [comment]
Lascio `FormActivity` così com'è, alla fine le 4 activity usate per la parte di login/registrazione usano i nostri oggetti `DatabaseReader` e `DatabaseWriter` ma ci sono anche `CreateTaskActivity` e `CreateRewardActivity` estendono `FormActivity` e lì interazione con il db non ce n'è, quindi meglio non mischiare troppe cose e lasciamo allo stato attuale
