### ISSUE TITLE
Cifratura password

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#59]
Implementare un metodo per la cifratura delle password (in modo da non salvarle tutte in plaintext) e sfruttare l'occasione per inserire gli `AsyncTask` nel progetto

**Comment by AndreaPitossi** [comment]
Fare attenzione che in fase di modifica dell'utente viene invocata la stessa funzione writeUser copiando la password appena letta dal DB; se si usa l'hash fare attenzione a copiare l'hash senza ri-hasharlo

**Comment by marcocadei** [comment]
L'unica password salvata è quella della casa (quella dell'utente è gestita completamente da firebase auth e noi non la salviamo nel db).
Il problema è che:
1. Non si trova un metodo buono che tutti approvano
2. Ci sono delle librerie, ma tutti sconsigliano di fare l'hash sul telefono in quanto molto pesante (sarebbe da fare sul server trasmettendo la password su SSL, ma noi ovviamente non possiamo)

In definitiva mi sa che questo lo dropperò, però mi guardo ancora un po' intorno

**Comment by marcocadei** [comment]
Ho trovato una libreria https://github.com/jeremyh/jBCrypt, ma per fare il codice con [AsyncTask](https://developer.android.com/reference/android/os/AsyncTask#the-4-steps) viene un bordello.
L'unica cosa che si potrebbe fare è non farlo async, ma è troppo una merda, mi rifiuto perfino io.

**Comment by marcocadei** [comment]
Alla fine ce l'ho fatta in modo figo con `Thread`

**Comment by gianluca150** [comment]
Come da commento precedente:
**Fare attenzione che in fase di modifica dell'utente viene invocata la stessa funzione writeUser copiando la password appena letta dal DB; se si usa l'hash fare attenzione a copiare l'hash senza ri-hasharlo**
