### ISSUE TITLE
Rifinitura activity signin/signup

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#64]
- JoinHomeActivity: gestione username duplicati (realizzare da zero), gestione aggiunta di una casa di cui l'utente è già membro (verificare in base alle regole di sicurezza finali impostate per firebase, richiede completamento #43)

Ricontrollare _tutte le 4 activity_ nei casi di errore (nome casa già esistente, nome utente già occupato, etc) dopo aver definito le regole di sicurezza *finali* che tutto vada come previsto e che la gestione degli errori è compatibile con le violazioni che si verificano

**Comment by marcocadei** [comment]
I controlli di case con nomi uguali e nickname duplicati in una casa ci sono già. Cosa manca ancora? @gianluca150

**Comment by gianluca150** [comment]
Manca la parte in cui dice di ricontrollare dopo aver impostato le regole di sicurezza finali su Firebase
