### ISSUE TITLE
Definire modalità di condivisione/passaggio degli oggetti tra activity

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#66]
In _tutte_ le activity (meno Enter/Signin/Signup) bisogna fare riferimento a quattro oggetti fondamentali che in pratica servono in ogni punto dell'app (User, Home, Member, UserHome), che vengono creati in fase di login/accesso alla casa
Bisogna stabilire come questi oggetti devono essere condivisi tra le varie activity (passaggio via Intent? salvataggio in shared preferences? [c'è chi dice persino fai un singleton accessibile da tutti?](https://stackoverflow.com/a/4878259)) e poi bisogna implementare questa cosa, per poter poi usare questi oggetti dato che servirà averceli nell'implementazione delle varie activity

**Comment by marcocadei** [comment]
Io partendo da questo link + facendo altre ricerche, come vi spiegavo oggi, mi dirigerei su un Singleton.
Se vi va bene chiudo.

**Comment by marcocadei** [comment]
Alla fine abbiamo usato la classe `Appartment` che utilizza il pattern singleton e sfrutta le `SharedPreferences` per garantire di avere sempre i dati
