### ISSUE TITLE
Cambiare stile activity con form

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#82]
Stile finale che devono avere tutte le activity con form (escluse solo signin e signup):
- Toolbar con nome activity (es. "Aggiungi premio")
- Form solito stile
- In cima alla form titolo grande + immagine (stile signin/signup) dove il titolo grande è la stessa cosa scritta nell'appbar

**Comment by AndreaPitossi** [comment]
Implementato lasciando alle activity gli stessi title che avevano già
