### ISSUE TITLE
Implementare cache Firebase

### ISSUE THREAD

**Issue by gianluca150** [MarcoCadei/APPartment#84]
Modificare ViewModel in modo che LiveData venga scaricato solo se i dati già non ci sono e in tutte le operazioni che modificano i dati aggiornare anche la cache a mano
https://pamartinezandres.com/lessons-learnt-the-hard-way-using-firebase-realtime-database-c609b52b9afb

**Comment by marcocadei** [comment]
Sembra che non scarichi davvero tutto e in ogni caso per quello che serve a noi funziona bene, quindi questo mi sa proprio che non lo faremo.
